-- Update cover_image and tags from exact WordPress thumbnails
UPDATE articles SET cover_image = '/images/posts/viva-interview.jpg', category = 'Новини', tags = '["Новини", "Інтервʼю", "Viva!"]' WHERE id IN ('art_1', '1');
UPDATE articles SET cover_image = '/images/posts/media-premiere.jpg', category = 'Новини', tags = '["Новини", "Медіа", "Події"]' WHERE id IN ('art_2', '2');
UPDATE articles SET cover_image = '/images/posts/forest-planting.jpg', category = 'Екологія', tags = '["Екологія", "Ліс", "Мої проєкти"]' WHERE id IN ('art_3', '3');
UPDATE articles SET cover_image = '/images/posts/creativity-presentation.jpg', category = 'Творчість', tags = '["Творчість", "Поезія", "Музика"]' WHERE id IN ('art_4', '4');

UPDATE articles SET cover_image = '/images/posts/wp_103_Gordinya-1200x675-1.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-103';
UPDATE articles SET cover_image = '/images/posts/wp_182_ImaRia.jpeg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-182';
UPDATE articles SET cover_image = '/images/posts/wp_191_100-топ.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-191';
UPDATE articles SET cover_image = '/images/posts/wp_200_3.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-200';
UPDATE articles SET cover_image = '/images/posts/wp_213_Випробування-приходять-для-духовного-і-ментального-зміцнення.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-213';
UPDATE articles SET cover_image = '/images/posts/wp_218_Що-я-ЖИВУ-зараз.jpg', category = 'Блог', tags = '["Блог"]' WHERE id = 'wp-218';
UPDATE articles SET cover_image = '/images/posts/wp_242_Про-мене-.png', category = 'Блог', tags = '["Про мене"]' WHERE id = 'wp-242';
UPDATE articles SET cover_image = '/images/posts/wp_393_Дизайн-без-назви-2.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-393';
UPDATE articles SET cover_image = '/images/posts/wp_399_Angelski-sili-Ukraini.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-399';
UPDATE articles SET cover_image = '/images/posts/wp_404_Do-chogo-nas-sponukaie-prostir.jpeg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-404';
UPDATE articles SET cover_image = '/images/posts/wp_412_День-Гідності-та-Свободи.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-412';
UPDATE articles SET cover_image = '/images/posts/wp_575_1.jpg', category = 'Блог', tags = '["Про мене"]' WHERE id = 'wp-575';
UPDATE articles SET cover_image = '/images/posts/wp_586_photo_5237904813419776215_y.jpg', category = 'Блог', tags = '["Блог"]' WHERE id = 'wp-586';
UPDATE articles SET cover_image = '/images/posts/viva-interview.jpg', category = 'Блог', tags = '["Блог"]' WHERE id = 'wp-1555';
UPDATE articles SET cover_image = '/images/posts/viva-interview.jpg', category = 'Блог', tags = '["Блог"]' WHERE id = 'wp-2810';
UPDATE articles SET cover_image = '/images/posts/viva-interview.jpg', category = 'Блог', tags = '["Блог"]' WHERE id = 'wp-3289';
UPDATE articles SET cover_image = '/images/posts/wp_593_358095877_235522099335057_7901617062961740807_n-1.jpg', category = 'Творчість', tags = '["Творчість"]' WHERE id = 'wp-593';
UPDATE articles SET cover_image = '/images/posts/wp_601_бізнес34-2048x1341-2.webp', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-601';
UPDATE articles SET cover_image = '/images/posts/wp_623_1.jpg', category = 'Блог', tags = '["Про мене"]' WHERE id = 'wp-623';
UPDATE articles SET cover_image = '/images/posts/wp_626_бізнес34-2048x1341-2.webp', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-626';
UPDATE articles SET cover_image = '/images/posts/wp_631_358095877_235522099335057_7901617062961740807_n-1.jpg', category = 'Творчість', tags = '["Творчість"]' WHERE id = 'wp-631';
UPDATE articles SET cover_image = '/images/posts/wp_642_photo_5237904813419776215_y.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-642';
UPDATE articles SET cover_image = '/images/posts/wp_807_Ти-—-Зірка🌟✨Центруйте-в-собі-енергію.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-807';
UPDATE articles SET cover_image = '/images/posts/wp_810_Соловіче.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-810';
UPDATE articles SET cover_image = '/images/posts/wp_813_pexels-photo-531756.jpeg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-813';
UPDATE articles SET cover_image = '/images/posts/wp_817_Тримаємось-за-світло-серця-і-стальні-нерви.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-817';
UPDATE articles SET cover_image = '/images/posts/wp_821_Щасливі-люди-живуть-на-високій-швидкості.png', category = 'Блог', tags = '["Мої блоги", "Рецепти"]' WHERE id = 'wp-821';
UPDATE articles SET cover_image = '/images/posts/wp_826_Сферическая-.jpg', category = 'Творчість', tags = '["Творчість"]' WHERE id = 'wp-826';
UPDATE articles SET cover_image = '/images/posts/wp_829_photo_5307751465667906277_y.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-829';
UPDATE articles SET cover_image = '/images/posts/wp_833_хранителі-частот.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-833';
UPDATE articles SET cover_image = '/images/posts/wp_842_слова-крила.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-842';
UPDATE articles SET cover_image = '/images/posts/wp_847_31.10.22.jpg', category = 'Блог', tags = '["Мої блоги", "Рецепти"]' WHERE id = 'wp-847';
UPDATE articles SET cover_image = '/images/posts/wp_850_час-на-.jpg', category = 'Блог', tags = '["Голос Душі", "Мої блоги"]' WHERE id = 'wp-850';
UPDATE articles SET cover_image = '/images/posts/wp_853_аРетрит.jpg', category = 'Блог', tags = '["Мої блоги", "Подорожі зі смислом"]' WHERE id = 'wp-853';
UPDATE articles SET cover_image = '/images/posts/wp_862_Дозволь-собі-Гордість-бути-Жінкою.jpg', category = 'Блог', tags = '["Голос Душі", "Мої блоги"]' WHERE id = 'wp-862';
UPDATE articles SET cover_image = '/images/posts/wp_865_Чим-я-живу-Блог-пульсара.jpg', category = 'Блог', tags = '["Мої блоги", "Рецепти"]' WHERE id = 'wp-865';
UPDATE articles SET cover_image = '/images/posts/wp_873_Ретрит.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-873';
UPDATE articles SET cover_image = '/images/posts/wp_876_Безумовна-Любов-–-безстрашна-Фінал-марафону-Цілісність.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-876';
UPDATE articles SET cover_image = '/images/posts/wp_884_Настройка.jpg', category = 'Творчість', tags = '["Творчість"]' WHERE id = 'wp-884';
UPDATE articles SET cover_image = '/images/posts/wp_915_personal-consultation.jpg', category = 'Блог', tags = '["Про мене"]' WHERE id = 'wp-915';
UPDATE articles SET cover_image = '/images/posts/wp_1010_Happy-.jpg', category = 'Блог', tags = '["Мої блоги", "Рецепти"]' WHERE id = 'wp-1010';
UPDATE articles SET cover_image = '/images/posts/wp_1023_photo_5357149959008408132_y.jpg', category = 'Блог', tags = '["Про мене"]' WHERE id = 'wp-1023';
UPDATE articles SET cover_image = '/images/posts/wp_1120_IMG_20240220_073305_048.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1120';
UPDATE articles SET cover_image = '/images/posts/wp_1123_Новий-світ.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1123';
UPDATE articles SET cover_image = '/images/posts/wp_1126_358095877_235522099335057_7901617062961740807_n-1.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1126';
UPDATE articles SET cover_image = '/images/posts/wp_1128_IMG_3918.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1128';
UPDATE articles SET cover_image = '/images/posts/wp_1131_Час.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1131';
UPDATE articles SET cover_image = '/images/posts/wp_1134_photo-58-scaled.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1134';
UPDATE articles SET cover_image = '/images/posts/wp_1257_khram.jpg', category = 'Блог', tags = '["Голос Душі", "Мої блоги"]' WHERE id = 'wp-1257';
UPDATE articles SET cover_image = '/images/posts/wp_1351_1.png', category = 'Блог', tags = '["Мої блоги", "Розвиток"]' WHERE id = 'wp-1351';
UPDATE articles SET cover_image = '/images/posts/wp_1355_Любов.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1355';
UPDATE articles SET cover_image = '/images/posts/wp_1412_photo_5400017971755211885_y.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-1412';
UPDATE articles SET cover_image = '/images/posts/wp_1500_Дякую-вам-за-ВАС-любі-Жінки-🪷😍🫶.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1500';
UPDATE articles SET cover_image = '/images/posts/wp_1617_Своя-Сила.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1617';
UPDATE articles SET cover_image = '/images/posts/wp_1621_Ретрит.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1621';
UPDATE articles SET cover_image = '/images/posts/wp_1655_photo_5397743876766294483_y.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1655';
UPDATE articles SET cover_image = '/images/posts/wp_1682_32.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-1682';
UPDATE articles SET cover_image = '/images/posts/wp_1735_photo_5219708102138517787_y-1.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1735';
UPDATE articles SET cover_image = '/images/posts/wp_1739_Бесіди-з-Ангелами.png', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-1739';
UPDATE articles SET cover_image = '/images/posts/wp_1746_Презентація.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1746';
UPDATE articles SET cover_image = '/images/posts/wp_1862_photo_5311999295697836140_y.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1862';
UPDATE articles SET cover_image = '/images/posts/wp_1867_Дизайн-без-назви-2.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1867';
UPDATE articles SET cover_image = '/images/posts/wp_1869_Дизайн-без-назви-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1869';
UPDATE articles SET cover_image = '/images/posts/wp_1876_440749450_422385353982063_7952801425827297287_n.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1876';
UPDATE articles SET cover_image = '/images/posts/wp_1879_maxresdefault.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1879';
UPDATE articles SET cover_image = '/images/posts/wp_1903_ЩАСТЯ-Є-1.jpg', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-1903';
UPDATE articles SET cover_image = '/images/posts/wp_1907_447901709_438208815733050_9067795409593118776_n.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1907';
UPDATE articles SET cover_image = '/images/posts/wp_1913_448204632_440615082159090_7457275328796169039_n.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1913';
UPDATE articles SET cover_image = '/images/posts/wp_1933_Історія-Роду-Людського.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1933';
UPDATE articles SET cover_image = '/images/posts/wp_1936_IMARIA.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1936';
UPDATE articles SET cover_image = '/images/posts/wp_1939_Творчість-це-процес.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1939';
UPDATE articles SET cover_image = '/images/posts/wp_1961_Чоловікам-.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1961';
UPDATE articles SET cover_image = '/images/posts/wp_1965_Відповідальність.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1965';
UPDATE articles SET cover_image = '/images/posts/wp_1968_Егрегор.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1968';
UPDATE articles SET cover_image = '/images/posts/wp_1971_Жіноча-сила.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1971';
UPDATE articles SET cover_image = '/images/posts/wp_1976_Сатсанг.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1976';
UPDATE articles SET cover_image = '/images/posts/wp_1984_Ретрит-Ти-перлина.jpg', category = 'Новини', tags = '["Новини", "Події"]' WHERE id = 'wp-1984';
UPDATE articles SET cover_image = '/images/posts/wp_1992_✨IMARIASPACE✨.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-1992';
UPDATE articles SET cover_image = '/images/posts/wp_2001_888.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2001';
UPDATE articles SET cover_image = '/images/posts/wp_2005_Нагорода.jpg', category = 'Новини', tags = '["Новини", "Події"]' WHERE id = 'wp-2005';
UPDATE articles SET cover_image = '/images/posts/wp_2020_Камінь.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2020';
UPDATE articles SET cover_image = '/images/posts/wp_2027_1.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2027';
UPDATE articles SET cover_image = '/images/posts/wp_2035_послання.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2035';
UPDATE articles SET cover_image = '/images/posts/wp_2039_Ретрит.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2039';
UPDATE articles SET cover_image = '/images/posts/wp_2074_Ірина-Заверуха.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2074';
UPDATE articles SET cover_image = '/images/posts/wp_2080_Дизайн-без-назви-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2080';
UPDATE articles SET cover_image = '/images/posts/wp_2083_Дизайн-без-назви-3.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2083';
UPDATE articles SET cover_image = '/images/posts/wp_2087_Бесіди-з-Ангелами.png', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-2087';
UPDATE articles SET cover_image = '/images/posts/wp_2122_Любити-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2122';
UPDATE articles SET cover_image = '/images/posts/wp_2135_Любити.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2135';
UPDATE articles SET cover_image = '/images/posts/wp_2140_photo_5354975885217879519_y-1.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2140';
UPDATE articles SET cover_image = '/images/posts/wp_2143_466048546_549690381251559_8924184413224731640_n.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2143';
UPDATE articles SET cover_image = '/images/posts/wp_2146_zaverukha.com_.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2146';
UPDATE articles SET cover_image = '/images/posts/wp_2149_zaverukha.com-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2149';
UPDATE articles SET cover_image = '/images/posts/wp_2152_zaverukha.com-3.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2152';
UPDATE articles SET cover_image = '/images/posts/wp_2163_zaverukha.com_-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2163';
UPDATE articles SET cover_image = '/images/posts/wp_2166_zaverukha.com-1-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2166';
UPDATE articles SET cover_image = '/images/posts/wp_2169_Ірина-Заверуха.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2169';
UPDATE articles SET cover_image = '/images/posts/wp_2384_zaverukha.com_.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2384';
UPDATE articles SET cover_image = '/images/posts/wp_2488_Бесіди-з-Ангелами-1.png', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-2488';
UPDATE articles SET cover_image = '/images/posts/wp_2562_Своя-Сила.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2562';
UPDATE articles SET cover_image = '/images/posts/wp_2568_zaverukha.com-2.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2568';
UPDATE articles SET cover_image = '/images/posts/wp_2571_zaverukha.com-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2571';
UPDATE articles SET cover_image = '/images/posts/wp_2596_476444009_616712577882672_5706620014308267673_n.jpg', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-2596';
UPDATE articles SET cover_image = '/images/posts/wp_2599_zaverukha.com-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2599';
UPDATE articles SET cover_image = '/images/posts/wp_2647_5357502631657991216.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-2647';
UPDATE articles SET cover_image = '/images/posts/wp_2710_5249044154699347549-1.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-2710';
UPDATE articles SET cover_image = '/images/posts/wp_2728_zaverukha.com-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2728';
UPDATE articles SET cover_image = '/images/posts/wp_2738_zaverukha.com-2.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2738';
UPDATE articles SET cover_image = '/images/posts/wp_2743_2-IMARIA-Academia-банер.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2743';
UPDATE articles SET cover_image = '/images/posts/wp_2770_zaverukha.com_-1.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2770';
UPDATE articles SET cover_image = '/images/posts/wp_2773_photo_5312259759694541521_y.jpg', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-2773';
UPDATE articles SET cover_image = '/images/posts/wp_2791_zaverukha.com-1.png', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-2791';
UPDATE articles SET cover_image = '/images/posts/wp_2795_zaverukha.com_.png', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-2795';
UPDATE articles SET cover_image = '/images/posts/wp_2799_zaverukha.com_-1.png', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-2799';
UPDATE articles SET cover_image = '/images/posts/wp_2827_zaverukha.com-1-1.png', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-2827';
UPDATE articles SET cover_image = '/images/posts/wp_2837_zaverukha.com_.png', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-2837';
UPDATE articles SET cover_image = '/images/posts/wp_2861_photo_5271746849318573747_y.jpg', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-2861';
UPDATE articles SET cover_image = '/images/posts/wp_2904_48.jpg', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-2904';
UPDATE articles SET cover_image = '/images/posts/wp_2906_5390977400604589285.jpg', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-2906';
UPDATE articles SET cover_image = '/images/posts/wp_2938_photo_5271746849318573541_y.jpg', category = 'Блог', tags = '["Блог"]' WHERE id = 'wp-2938';
UPDATE articles SET cover_image = '/images/posts/wp_3004_формат-ютюб-1.jpg', category = 'Блог', tags = '["Мої блоги"]' WHERE id = 'wp-3004';
UPDATE articles SET cover_image = '/images/posts/wp_3014_photo_5271746849318573747_y.jpg', category = 'Блог', tags = '["Блог"]' WHERE id = 'wp-3014';
UPDATE articles SET cover_image = '/images/posts/wp_3019_photo_5271746849318573541_y.jpg', category = 'Блог', tags = '["Про мене"]' WHERE id = 'wp-3019';
UPDATE articles SET cover_image = '/images/posts/wp_3244_2026-06-29-11.34.28.jpg', category = 'Новини', tags = '["Мої блоги", "Новини"]' WHERE id = 'wp-3244';
UPDATE articles SET cover_image = '/images/posts/wp_3298_61-1.jpg', category = 'Новини', tags = '["Новини"]' WHERE id = 'wp-3298';
